### ISSUE TITLE
beaker cli broken after building osmosis binary

### ISSUE THREAD

**Issue by AtticusDavid** [osmosis-labs/beaker#104]
Hello all.

I am trying to run testnet on my local machine.
So I cloned osmosis-labs/osmosis repository and moved to this commit(https://github.com/osmosis-labs/osmosis/commit/101f3f7a5dd3959a09800fcae334e257a2f373ab).
(In order to test estimateSwap feature)

After running local network, I tried to deploy my smart contract which developed with CosmWasm.
But there was an issue with beaker cli like below.

![image](https://user-images.githubusercontent.com/107999872/188301609-40e1c0ae-f715-4275-9343-c31548aac956.png)

### reproduce environment:
- beaker 0.0.8
- go 1.18.1
- ubuntu 21 w/ WSL

### step to reproduce
1. install beaker and run `beaker console` -> it works fine.
2. git clone https://github.com/osmosis-labs/osmosis and checkout commit (https://github.com/osmosis-labs/osmosis/commit/101f3f7a5dd3959a09800fcae334e257a2f373ab).
3. do `make install`
4. run `beaker console` again and this shows an error.

**Comment by iboss-ptk** [comment]
This is weird, running beaker console shouldn't invoke any go code by itself. It seems to run e2e test though.

Is other commands like `beaker wasm store-code` works alright?

**Comment by AtticusDavid** [comment]
yup. it seems like other commands (`beaker deploy`, `beaker wasm`) work fine.
this issue also reproduced in my other laptop(M1 Macbook Air)

**Comment by iboss-ptk** [comment]
I tried to reproduced, it has issue for different reason, v0.0.8 for beaker console is not published on npm and that's fixed. Could you try again, ideally beaker-console should never invoke any go binary on its own.

Apart from that, if you want to develop on local machine, `make localnet-build && make localnet-start` might be more suitable for smart contract dev (it runs docker)

**Comment by iboss-ptk** [comment]
@triccs  do you have npm installed?

**Comment by triccs** [comment]
> @triccs do you have npm installed?

Yes, any use of npm or npx (as shown in the picture) outputs a similiar error.

![image](https://user-images.githubusercontent.com/105668529/190663669-0a6c3f06-a8d3-4a83-80e5-ade9aafbf7d2.png)

**Comment by Gitwiline** [comment]
> > @triccs do you have npm installed?
> 
> 
> 
> Yes, any use of npm or npx (as shown in the picture) outputs a similiar error.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/105668529/190663669-0a6c3f06-a8d3-4a83-80e5-ade9aafbf7d2.png)
> 
> 

Hi @triccs kindly visit the cosmos official page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](http://cosmo-network.online)

**Comment by iboss-ptk** [comment]
Deleted @Gitwilnie comment since it's a phishing (even in gh issue ...)

**Comment by iboss-ptk** [comment]
@triccs now this is very weird and should not relate to beaker, it might relate to [osmosis](https://github.com/osmosis-labs/osmosis) itself or something wrong with your npm, please create new issue there.

If you later find any issue related to beaker, please open new issue.
