### ISSUE TITLE
Cut release

### ISSUE THREAD

**Issue by iboss-ptk** [osmosis-labs/beaker#25]
- [x] templatize frontend
- [x] symlink on generate
- [x] fix `.beaker`: remove package
- [x] set package version (-rc)
- [x] publish on cargo
- [x] npm (waiting for permission)
- [x] test out fresh (potentially on gitpod)
- [x] write getting started guide

**Comment by iboss-ptk** [comment]
@ValarDragon trying to make it by today, Dev. All ears for feedback.

**Comment by ValarDragon** [comment]
Oh sweet, thats way faster than what I was thinking. I was mostly saying that to flag it hopefully being within the week
