### ISSUE TITLE
`Beaker new` project should have values in `.gitignore`

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/beaker#34]
Currently a project generated from `beaker new counter-dapp` has a blank gitignore, this is one step we should automate out!

- [ ] use https://github.com/github/gitignore/blob/main/Rust.gitignore as base
- [ ] add `artifacts` (for wasm artifacts)
- [ ] add `**/state.local.json`

**Comment by iboss-ptk** [comment]
yes, will add `target` and `artifacts`, and other rust related stuffs then (https://github.com/github/gitignore/blob/main/Rust.gitignore). Let me know if there are more to add!
