### ISSUE TITLE
Use keyring for signing (Signer-account)

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/beaker#46]
For the `signer-account` option I think having a few predefined ones works well for localosmosis but for testnet/mainnet it would be best to use:

- use system keyring so that I can use my own keys
- option to specify the keyring backend

https://docs.cosmos.network/master/run-node/keyring.html

I guess we could call them: 
`system-signer-account` && `beaker-signer-account`?

This way we can allow people to request testnet tokens via the faucet for their own addresses, and eventually add an option to the faucet to approve contracts as well as we discussed yesterday.

**Comment by daniel-farina** [comment]
Also @iboss-ptk  asked: 
What is the process with Ledger?

**Comment by daniel-farina** [comment]
Maybe we should try to do this manually first to understand the process.

**Comment by ValarDragon** [comment]
Is the goal to wrap the Osmosisd cli, or to directly access the keyrings themselves?

**Comment by iboss-ptk** [comment]
Should bet the latter, I think.
