### ISSUE TITLE
Docs: docker, rustup, accounts

### ISSUE THREAD

**Issue by fadeev** [osmosis-labs/beaker#71]
- [x] Prerequisites.
  - [x] Docker. It's fair to assume, that most people will be using Beaker with Local Osmosis. Makes sense to add Docker into prerequisites, so that a user has everything to go through a tutorial
  - [x] Rust. Pretty obvious, but a link to https://www.rust-lang.org/tools/install wouldn't hurt.
- [x] `rustup target add wasm32-unknown-unknown` has to be executed before [`beaker wasm deploy`](https://github.com/osmosis-labs/beaker/blob/d975f1d06b13ebcdc86dd22278c32ab0d753ef00/README.md?plain=1#L154)
- [x] Accounts. In the [frontend section](https://github.com/osmosis-labs/beaker/blob/d975f1d06b13ebcdc86dd22278c32ab0d753ef00/README.md?plain=1#L330) adding a link to local Osmosis accounts with a short description of how to add them in Keplr might be useful for devs new to Cosmos.
- [x] Add doc for type gen

**Comment by iboss-ptk** [comment]
sounds good! thanks for suggestion :D

**Comment by iboss-ptk** [comment]
for `rustup target add wasm32-unknown-unknown`, it's now auto detect and install if not exist (#81)
