### ISSUE TITLE
beaker warm: Error: No such file or directory (os error 2) on macOS

### ISSUE THREAD

**Issue by miohtama** [osmosis-labs/beaker#93]
If you get the following error on macOS: (M1)

```
Error: No such file or directory (os error 2)
```

when running:

```shell
beaker wasm deploy counter --signer-account test1 --no-wasm-opt --raw '{ "count": 0 }' --admin signer
```

or 

```shell
beaker wasm build
```

Make sure you have Rust installed with wasm support using `rustup`. Rust from Homebrew might not work about.

How to fix:

```shell
brew uninstall rust  # rustup cannot coexist with brew installed rust
brew install rustup
rustup target add wasm32-unknown-unknown
```

**Comment by iboss-ptk** [comment]
Probably not need the last line to fix the issue but it does requires rustup. Thank you will add requirement on the README.md

https://github.com/osmosis-labs/beaker/blob/v0.0.7/packages/cli/src/modules/wasm/ops/build.rs#L18,L44
